#define ROOT_ID 1

// #define LOG_CONF_LEVEL_RPL LOG_LEVEL_INFO
#define LOG_CONF_WITH_COMPACT_ADDR 1

// /* Provisioning */
#define NETSTACK_MAX_ROUTE_ENTRIES 25
#define NBR_TABLE_CONF_MAX_NEIGHBORS 8
#define UIP_CONF_BUFFER_SIZE 512

// /* RPL Objective Function */
// #define RPL_CONF_OF_OCP RPL_OCP_OF0
