TARGET = cooja
CONTIKI_PROJECT = node
all: $(CONTIKI_PROJECT)

CONTIKI = ../contiki-ng
include $(CONTIKI)/Makefile.include

#default setting from Makefile.include
#MAKE_MAC ?= MAKE_MAC_CSMA
#MAKE_NET ?= MAKE_NET_IPV6
#MAKE_ROUTING ?= MAKE_ROUTING_RPL_LITE

#no radio duty cycle using CSMA, but TSCH will contain RDC by its own